import type { Idea, Insight, Project, User } from "./types";

export const SEED_USER: User = {
  id: "u1",
  name: "Rogerio Alves",
  email: "rogerio@hubflow.io",
  company: "HUBFLOW Labs",
  role: "Innovation Manager",
  createdAt: "2025-01-12T09:00:00.000Z",
};

export const SEED_PROJECTS: Project[] = [
  {
    id: "p1",
    name: "Smart Onboarding AI",
    description: "AI-guided onboarding that cuts time-to-value for new SaaS customers.",
    sector: "Fintech",
    maturity: "MVP",
    status: "InProgress",
    owner: "Rogerio Alves",
    createdAt: "2025-03-02T10:00:00.000Z",
  },
  {
    id: "p2",
    name: "Green Logistics Platform",
    description: "Route optimization that reduces emissions for last-mile delivery.",
    sector: "Logistics",
    maturity: "Validation",
    status: "Approved",
    owner: "Marina Costa",
    createdAt: "2025-02-18T14:30:00.000Z",
  },
  {
    id: "p3",
    name: "Tele-Triage Assistant",
    description: "Conversational triage for clinics to prioritize patients faster.",
    sector: "Healthtech",
    maturity: "Ideation",
    status: "InProgress",
    owner: "Rogerio Alves",
    createdAt: "2025-04-09T08:15:00.000Z",
  },
  {
    id: "p4",
    name: "Retail Demand Sensing",
    description: "Predictive restocking using local trend and weather signals.",
    sector: "Retail",
    maturity: "Scale",
    status: "Archived",
    owner: "Diego Lima",
    createdAt: "2024-11-22T16:45:00.000Z",
  },
];

export const SEED_IDEAS: Idea[] = [
  {
    id: "i1",
    title: "Transparent usage-based pricing",
    description: "Let customers pay only for what they use, with a live cost dashboard.",
    type: "BusinessModel",
    status: "InReview",
    projectId: "p1",
    author: "Rogerio Alves",
    sector: "Fintech",
    tags: ["pricing", "transparency"],
    createdAt: "2025-03-12T11:00:00.000Z",
  },
  {
    id: "i2",
    title: "Carbon score per delivery",
    description: "Show end-customers the carbon footprint of each delivery option.",
    type: "Product",
    status: "Approved",
    projectId: "p2",
    author: "Marina Costa",
    sector: "Logistics",
    tags: ["sustainability", "esg"],
    createdAt: "2025-02-25T09:30:00.000Z",
  },
  {
    id: "i3",
    title: "Voice intake for clinics",
    description: "Patients describe symptoms by voice; AI structures the triage form.",
    type: "Service",
    status: "Draft",
    projectId: "p3",
    author: "Rogerio Alves",
    sector: "Healthtech",
    tags: ["voice", "ai", "triage"],
    createdAt: "2025-04-11T13:20:00.000Z",
  },
  {
    id: "i4",
    title: "Auto-restock micro-bundles",
    description: "Bundle slow + fast movers to optimize shelf space automatically.",
    type: "Process",
    status: "Rejected",
    projectId: "p4",
    author: "Diego Lima",
    sector: "Retail",
    tags: ["inventory"],
    createdAt: "2024-12-01T10:10:00.000Z",
  },
  {
    id: "i5",
    title: "Community-led feature voting",
    description: "Let power users vote and fund the next features to be built.",
    type: "Incremental",
    status: "Draft",
    projectId: null,
    author: "Rogerio Alves",
    sector: "Fintech",
    tags: ["community", "roadmap"],
    createdAt: "2025-05-03T15:40:00.000Z",
  },
];

export const SEED_INSIGHTS: Insight[] = [];